#pragma once

namespace bdn::android::wrapper
{
    // android/text/InputType.h
    enum class InputType : int
    {
        TYPE_CLASS_DATETIME = 4,
        TYPE_CLASS_NUMBER = 2,
        TYPE_CLASS_PHONE = 3,
        TYPE_CLASS_TEXT = 1,
        TYPE_DATETIME_VARIATION_DATE = 16,
        TYPE_DATETIME_VARIATION_NORMAL = 0,
        TYPE_DATETIME_VARIATION_TIME = 32,
        TYPE_MASK_CLASS = 15,
        TYPE_MASK_FLAGS = 16773120,
        TYPE_MASK_VARIATION = 4080,
        TYPE_NULL = 0,
        TYPE_NUMBER_FLAG_DECIMAL = 8192,
        TYPE_NUMBER_FLAG_SIGNED = 4096,
        TYPE_NUMBER_VARIATION_NORMAL = 0,
        TYPE_NUMBER_VARIATION_PASSWORD = 16,
        TYPE_TEXT_FLAG_AUTO_COMPLETE = 65536,
        TYPE_TEXT_FLAG_AUTO_CORRECT = 32768,
        TYPE_TEXT_FLAG_CAP_CHARACTERS = 4096,
        TYPE_TEXT_FLAG_CAP_SENTENCES = 16384,
        TYPE_TEXT_FLAG_CAP_WORDS = 8192,
        TYPE_TEXT_FLAG_IME_MULTI_LINE = 262144,
        TYPE_TEXT_FLAG_MULTI_LINE = 131072,
        TYPE_TEXT_FLAG_NO_SUGGESTIONS = 524288,
        TYPE_TEXT_VARIATION_EMAIL_ADDRESS = 32,
        TYPE_TEXT_VARIATION_EMAIL_SUBJECT = 48,
        TYPE_TEXT_VARIATION_FILTER = 176,
        TYPE_TEXT_VARIATION_LONG_MESSAGE = 80,
        TYPE_TEXT_VARIATION_NORMAL = 0,
        TYPE_TEXT_VARIATION_PASSWORD = 128,
        TYPE_TEXT_VARIATION_PERSON_NAME = 96,
        TYPE_TEXT_VARIATION_PHONETIC = 192,
        TYPE_TEXT_VARIATION_POSTAL_ADDRESS = 112,
        TYPE_TEXT_VARIATION_SHORT_MESSAGE = 64,
        TYPE_TEXT_VARIATION_URI = 16,
        TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = 144,
        TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = 160,
        TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = 208,
        TYPE_TEXT_VARIATION_WEB_PASSWORD = 224
    };
}