FROM ubuntu:16.04

ARG EMSCRIPTEN_VERSION=1.38.0-64bit
ARG NODE_VERSION=4.1.1-64bit

RUN apt-get update \
 && apt-get install -y \
    curl \
    unzip \
    xvfb \
    xauth \
	python \
    cmake \
    clang \
    git \
    default-jre \
    dbus-x11 \
    firefox

# JRE is needed because some optional parts of emscripten
# need java (for example the closure compiler)
# Firefox is installed so that we can run unit tests inside
# the docker container.


# get the emscripten sdk helper
# (manages emscripten SDK installations)
RUN mkdir /emsdk
RUN mkdir /userhome

WORKDIR /emsdk

# do the remaining emscripten setup as the user that we will end up being
ENV HOME=/userhome

RUN git clone https://github.com/juj/emsdk.git /emsdk

# no need to run emsdk update because we got the current version from github
RUN /emsdk/emsdk install emscripten-tag-$EMSCRIPTEN_VERSION
RUN /emsdk/emsdk activate emscripten-tag-$EMSCRIPTEN_VERSION
RUN /emsdk/emsdk install clang-tag-e$EMSCRIPTEN_VERSION
RUN /emsdk/emsdk activate clang-tag-e$EMSCRIPTEN_VERSION
RUN /emsdk/emsdk install node-$NODE_VERSION
RUN /emsdk/emsdk activate node-$NODE_VERSION

ENV EMSDK_BASE_DIR=/emsdk


# emscripten may try to create files in the emsdk directory
# when it is run. It will also try to create files in the home directory.
# Normally this would not be a problem, since docker processes
# inside the container usually run as root. But in some cases (for example,
# if the container is run from Jenkins), they will run as normal users.
# So we have to make sure that all users get to modify whatever they want
# in the home directory.
# The emscripten SDK directory is a similar case: emscripten may need to modify
# and create files there when we prepare or build the code.

RUN chmod -R go+rwX /userhome
RUN chmod -R go+rwX /emsdk




