#!/bin/bash

if [ -z "$1" ]
then
	PLATFORM="linux"
else
	PLATFORM="$1"
fi



if [ -z "$2" ]
then
	BUILD_SYSTEM="make"
else
	BUILD_SYSTEM="$2"
fi



python build.py prepare --platform "$PLATFORM" --build-system "$BUILD_SYSTEM" || exit 2

python build.py build --platform "$PLATFORM"  || exit 3


REPORT_DIR="`pwd`/reports"
if [ ! -d $REPORT_DIR ]
then
    mkdir $REPORT_DIR
fi


function runTestExe {
echo "Running tests: $1 $2"

OUTFILE=$REPORT_DIR/${1}_${PLATFORM}_${2}.xml
rm -f "$OUTFILE"
if [ "$PLATFORM" = "webems" ]
then
    # the javascript code does not have access to the filesystem.
    # So we have to use stdout (which gets piped through to us with
    # emrun magic).
    python build.py --platform $PLATFORM --config $2 --module $1 -- run --reporter junit > "$OUTFILE"

else
    # use the -o parameter if we have filesystem access
    python build.py --platform $PLATFORM --config Debug --module testboden -- run --reporter junit -o "$OUTFILE"
fi
}

runTestExe testboden Debug
runTestExe testboden Release
runTestExe testbodenui Debug
runTestExe testbodenui Release



