
macro(enable_automatic_reference_counting TARGET SCOPE)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_CXX_COMPILER_ID STREQUAL "Apple")
	    target_compile_options(${TARGET} ${SCOPE} "-fobjc-arc")
	endif()
endmacro()

macro(enable_warnings_as_errors TARGET SCOPE)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        target_compile_options(${TARGET} ${SCOPE} "-Werror")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${TARGET} ${SCOPE} "-Werror")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${TARGET} ${SCOPE} "/WX")
    else()
        message(WARNING "I Don't know how to enable warnings as errors on this platform! (${CMAKE_CXX_COMPILER_ID})")
    endif()
endmacro()

macro(enable_big_object_files TARGET SCOPE)
    if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        target_compile_options(${TARGET} ${SCOPE} "/bigobj")
    endif()
endmacro()

macro(enable_unicode TARGET SCOPE)
    target_compile_definitions(${TARGET} ${SCOPE} "UNICODE" "_UNICODE")
endmacro()

macro(enable_multicore_build TARGET SCOPE)
	if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		target_compile_options(${TARGET} ${SCOPE} "/MP")
	endif()
endmacro()
