macro(use_boden_template_info_plist TARGETNAME)
    if(BDN_PLATFORM_IOS)
        get_target_property(BODEN_CMAKE_SOURCE_DIR boden_cmake SOURCE_DIR)
        set_target_properties(${TARGETNAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST ${BODEN_CMAKE_SOURCE_DIR}/templates/IOSInfo.plist.in)
    elseif(BDN_PLATFORM_OSX)
        get_target_property(BODEN_CMAKE_SOURCE_DIR boden_cmake SOURCE_DIR)
        set_target_properties(${TARGETNAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST ${BODEN_CMAKE_SOURCE_DIR}/templates/OSXInfo.plist.in)
    endif()
endmacro()

macro(ios_setup_code_signing TARGETNAME)
    if(BDN_PLATFORM_IOS)
        set_xcode_property(${TARGETNAME} CODE_SIGN_STYLE Automatic)
        set_xcode_property(${TARGETNAME} CODE_SIGN_IDENTITY "iPhone Developer")

        if (DEFINED ENV{BODEN_TEAM_ID})
            set_xcode_property(${TARGETNAME} DEVELOPMENT_TEAM $ENV{BODEN_TEAM_ID})
        endif()
    endif()
endmacro()

macro(ios_set_appicon_asset_file TARGETNAME APP_ICON_NAME)
    if(BDN_PLATFORM_IOS)
        set_xcode_property(${TARGETNAME} ASSETCATALOG_COMPILER_APPICON_NAME ${APP_ICON_NAME})
    endif()
endmacro()

macro(ios_set_launchboard_file LAUNCHBOARD_NAME)
    SET(MACOSX_BUNDLE_LAUNCH_STORYBOARD ${LAUNCHBOARD_NAME})
endmacro()

macro(ios_configure_asset ASSET_LIST ASSET_FILE)
    if(BDN_PLATFORM_IOS)
        set_source_files_properties(${ASSET_FILE} PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
        list(APPEND ${ASSET_LIST} ${ASSET_FILE})
    endif()
endmacro()
