site_name: Boden Cross-Platform Framework

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'White'
  feature:
    tabs: true
  logo: 'boden-logo-header.svg'
  favicon: 'favicon-32x32.png'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/AshampooSystems'
    - type: 'twitter'
      link: 'https://twitter.com/bodenhq'

repo_url: 'https://github.com/AshampooSystems/boden'
repo_name: 'boden'
edit_uri: edit/master/docs/docs

extra_css:
  - 'stylesheets/cookieconsent.min.css'
  - 'stylesheets/boden.css'

extra_javascript:
  - 'javascripts/cookieconsent.min.js'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: 'docs'
  - admonition
  - meta
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs

nav:
  - Getting Started:
    - getting-started/index.md
    - getting-started/first_app.md
    - Building Boden:
      - getting-started/building/mac.md
      - getting-started/building/windows.md
      - getting-started/building/linux.md
    - Installing Dependencies:
      - getting-started/installing_dependencies/mac-ios.md
      - getting-started/installing_dependencies/mac-android.md
      - getting-started/installing_dependencies/windows.md
      - getting-started/installing_dependencies/linux.md
    - getting-started/troubleshooting/index.md
    - getting-started/faq.md
  - Guides:
    - guides/index.md
    - Fundamentals:
      - guides/fundamentals/properties.md
      - guides/fundamentals/resources.md
    - Extending Boden:
      - guides/extending/writing_view.md
      - guides/extending/writing_view_modules.md
      - guides/extending/wrap_java_class.md      
  - API Reference:
    - API Reference Overview: 'reference/index.md'
    - Foundation:
      - reference/foundation/application.md
      - reference/foundation/application_controller.md
      - reference/foundation/attributed_string.md
      - reference/foundation/color.md
      - reference/foundation/dispatch_queue.md
      - reference/foundation/font.md
      - reference/foundation/global_stack.md
      - reference/foundation/needs_init.md
      - reference/foundation/notifier.md
      - reference/foundation/path.md
      - reference/foundation/point.md
      - reference/foundation/property.md
      - reference/foundation/rect.md
      - reference/foundation/size.md
      - reference/foundation/stream_backing.md
      - reference/foundation/string.md
      - reference/foundation/transform_backing.md
    - UI:
      - reference/ui/autocorrection_type.md
      - reference/ui/button.md
      - reference/ui/checkbox.md
      - reference/ui/click_event.md
      - reference/ui/container_view.md
      - reference/ui/core_less.md
      - reference/ui/image_view.md
      - reference/ui/label.md
      - reference/ui/layout.md
      - reference/ui/list_view.md
      - reference/ui/list_view_data_source.md
      - reference/ui/navigation_view.md
      - Platforms:
        - iOS:
          - reference/ui/ios/view_core.md
      - reference/ui/return_key_type.md
      - reference/ui/scroll_view.md
      - reference/ui/slider.md
      - reference/ui/styler.md
      - reference/ui/submit_event.md
      - reference/ui/switch.md
      - reference/ui/text.md
      - reference/ui/text_field.md
      - reference/ui/text_input_type.md
      - reference/ui/text_overflow.md
      - reference/ui/tri_state.md
      - reference/ui/view.md
      - reference/ui/view_core.md
      - reference/ui/view_core_factory.md
      - reference/ui/view_event.md
      - reference/ui/web_view.md
      - reference/ui/window.md
      - Yoga:
          - reference/ui/yoga/layout.md
    - Net:
      - reference/net/http.md
      - reference/net/http_request.md
      - reference/net/http_response.md
    - Extra Modules:
      - Lottie:
        - reference/extra-modules/lottie/lottie_view.md
  - Legal:
    - Legal: 'https://www.personizer.com/en/legal/'
    - legal/privacy_policy.md
    - Licensing: 
      - Overview: 'legal/licensing/index.md'
      - FDL 1.3: 'legal/licensing/fdl-1.3.md'
      - GPL 2: 'legal/licensing/gpl-2.md'
      - GPL 3: 'legal/licensing/gpl-3.md'
      - LGPL 2.1: 'legal/licensing/lgpl-2.1.md'
      - LGPL 3: 'legal/licensing/lgpl-3.md'
  - Feedback:
    - Getting in Touch with the Boden Team: feedback/index.md
    - Reporting Bugs: feedback/reporting-bugs.md
    - Contributing: feedback/contributing.md

google_analytics:
  - 'GTM-MP93ZKM'
  - 'auto'

copyright: 'Copyright &copy; 2021 Personizer GmbH & Co. KG'
site_description: 'Boden is the new cross-platform framework for building real native mobile apps using native widgets and modern C++17. Boden is free and open source.'